disabled = false
languageCode = "fr"
languageName = "French"
weight = 1
title = "Conception Logicielle"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 January 2006"
secondaryLogo = "."
description = "Introduction à la conception et à l'ingénieurie logicielle"


