disabled = false
languageCode = "fr"
languageName = "French"
weight = 1
title = "üè† Conception Logicielle ENSAI"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 January 2006"
secondaryLogo = "."
description = "Introduction √† la conception et √† l'ing√©nieurie logicielle"


