[[main]]
  name = "Cours"
  pageRef = "cours"
  pre = "bars"
  weight = 20

[[main]]
  name = "Git Avancé"
  parent = "Cours"
  pageRef = "cours/git-avance"
  weight = 1
[[main]]
  name = "Architecture applicative"
  parent = "Cours"
  pageRef = "cours/architecture-applicative"
  weight = 2
[[main]]
  name = "Gestion de packages et portabilité"
  parent = "Cours"
  pageRef = "cours/gestionnaire-de-package"
  weight = 3
[[main]]
  name = "Configuration applicative"
  parent = "Cours"
  pageRef = "cours/configuration"
  weight = 4
[[main]]
  name = "Bonnes pratiques"
  parent = "Cours"
  pageRef = "cours/bonnes-pratiques"
  weight = 5
[[main]]
  name = "Analyse statique"
  parent = "Cours"
  pageRef = "cours/analyse-statique"
  weight = 6
[[main]]
  name = "Automatisation des contrôles"
  parent = "Cours"
  pageRef = "cours/automatisation-controle"
  weight = 8

[[main]]
  name = "Projets"
  pre = "worktree"
  pageRef = "projets"
  weight = 20

[[main]]
  name = "Blog"
  pre = "edit"
  pageRef = "blog"
  weight = 20

[[main]]
  identifier = "github-link"
  pre = "github"
  url = "https://github.com/conception-logicielle-ensai/cours"
  weight = 40